# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: check-toml
  - id: end-of-file-fixer

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2

- repo: local
  hooks:
  - id: poetry check
    name: Check poetry config
    entry: poetry check
    language: system
    pass_filenames: false

  - id: poetry install
    name: Install dependencies with Poetry
    entry: poetry install
    language: system
    pass_filenames: false
    args:
    - "--with"
    - "dev"

  - id: ruff-format
    name: ruff format
    entry: poetry run ruff format
    language: system
    types_or: [python, pyi]

  - id: ruff-check
    name: ruff check
    entry: poetry run ruff check --fix
    language: system
    types_or: [python, pyi]
