# Generated by Django 5.1.3 on 2024-11-18 06:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
            ],
            options={
                "db_table": "user",
                "indexes": [
                    models.Index(fields=["email"], name="user_email_7bbb4c_idx"),
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="user_first_n_3f9974_idx",
                    ),
                ],
            },
        ),
    ]
