# Generated by Django 5.1.3 on 2024-11-18 06:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "db_table": "ticket",
                "indexes": [
                    models.Index(fields=["token"], name="ticket_token_7634ce_idx"),
                    models.Index(fields=["order_id"], name="ticket_order_i_5e884d_idx"),
                ],
            },
        ),
    ]
