# Generated by Django 5.1.3 on 2024-11-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["created_at"], name="ticket_created_807d9e_idx"),
        ),
    ]
