# Generated by Django 5.1.3 on 2024-11-18 06:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "order",
                "indexes": [
                    models.Index(fields=["name"], name="order_name_894b67_idx"),
                    models.Index(fields=["user_id"], name="order_user_id_60f97d_idx"),
                ],
            },
        ),
    ]
